# Generated by Django 5.2 on 2025-12-13 13:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DoctorProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "specialty",
                    models.CharField(
                        choices=[
                            ("cardiologist", "Cardiologist"),
                            ("neurologist", "Neurologist"),
                            ("orthopedic", "Orthopedic Surgeon"),
                            ("pediatrician", "Pediatrician"),
                            ("dermatologist", "Dermatologist"),
                            ("oncologist", "Oncologist"),
                            ("emergency", "Emergency Medicine"),
                            ("radiologist", "Radiologist"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("cardiology", "Cardiology Dept."),
                            ("neurology", "Neurology Dept."),
                            ("orthopedics", "Orthopedics Dept."),
                            ("pediatrics", "Pediatrics Dept."),
                            ("dermatology", "Dermatology Dept."),
                            ("oncology", "Oncology Dept."),
                            ("emergency", "Emergency Dept."),
                            ("radiology", "Radiology Dept."),
                        ],
                        max_length=30,
                    ),
                ),
                ("description", models.TextField(max_length=255)),
                ("years_of_experience", models.PositiveIntegerField()),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="static/img/doctors"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doctor_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
