# Generated by Django 5.2 on 2025-12-13 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctorprofile",
            name="reviews",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="doctorprofile",
            name="stars",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name="doctorprofile",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="img/doctors"),
        ),
    ]
