# Generated by Django 5.2 on 2025-12-13 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0002_doctorprofile_reviews_doctorprofile_stars_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctorprofile",
            name="reviews",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
