# Generated by Django 5.2 on 2025-12-13 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0003_alter_doctorprofile_reviews"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctorprofile",
            name="stars",
            field=models.FloatField(blank=True, max_length=5, null=True),
        ),
    ]
