# Generated by Django 5.2 on 2025-12-13 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0004_alter_doctorprofile_stars"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctorprofile",
            name="last_seen",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="doctorprofile",
            name="reviews",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
